# Generated by Django 5.2.13 on 2026-04-23 09:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=200, unique=True)),
                ('project_code_normalized', models.CharField(db_index=True, max_length=200, unique=True)),
                ('module_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('status', models.CharField(choices=[('orphan', 'Orphan'), ('new', 'New'), ('qualified', 'Qualified'), ('sent_quote', 'Sent quote'), ('contract', 'Contract'), ('prepayment', 'Prepayment'), ('production', 'Production'), ('installation', 'Installation'), ('delivered', 'Delivered'), ('lost', 'Lost')], default='new', max_length=20)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='clients.client')),
            ],
        ),
    ]
