# Generated by Django 5.2.13 on 2026-04-23 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('archicad', 'ArchiCAD'), ('manual', 'Manual'), ('client_revision', 'Client revision')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_client', 'Sent to client'), ('accepted', 'Accepted'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('frozen_data', models.JSONField(blank=True, null=True)),
                ('plan_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('plan_preview_png_path', models.CharField(blank=True, max_length=500, null=True)),
                ('plan_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('quote_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('quote_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_versions', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='deals.deal')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('deal', 'version_number'), name='uniq_deal_version_number')],
            },
        ),
    ]
