# Generated by Django 5.2.13 on 2026-04-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='code_client_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия / компания (в коде проекта)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='code_site_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название участка (в коде проекта)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='project_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Код проекта'),
        ),
    ]
