# Generated by Django 5.2.13 on 2026-04-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_code_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='mortgage_required',
            field=models.BooleanField(default=False, verbose_name='Ипотека'),
        ),
        migrations.AddField(
            model_name='deal',
            name='target_deal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выхода на сделку'),
        ),
    ]
