# Generated by Django 5.2.13 on 2026-04-24 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_add_dashboard_lead_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='module_count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
