# Generated by Django 5.2.13 on 2026-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='source',
            field=models.CharField(choices=[('client', 'Client'), ('designer', 'Designer'), ('sales', 'Sales'), ('system', 'System')], max_length=20),
        ),
    ]
