# Generated by Django 5.2.13 on 2026-05-06 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_alter_deal_code_client_name_verbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff')], max_length=20)),
                ('author_email', models.EmailField(blank=True, default='', max_length=254)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_client_messages', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to='deals.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealClientMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('project_file', 'Project file'), ('voice', 'Voice')], max_length=30)),
                ('mime_type', models.CharField(blank=True, default='', max_length=150)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='deals.dealclientmessage')),
                ('project_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_message_attachments', to='deals.projectfile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DealClientPortalOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts_left', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_portal_otps', to='deals.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealClientPortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('session_token_hash', models.CharField(db_index=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_portal_sessions', to='deals.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dealclientmessage',
            index=models.Index(fields=['deal', '-created_at'], name='deal_client_msg_list_idx'),
        ),
        migrations.AddIndex(
            model_name='dealclientmessageattachment',
            index=models.Index(fields=['message', 'kind'], name='deal_client_att_msg_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='dealclientportalotp',
            index=models.Index(fields=['deal', 'email', '-created_at'], name='deal_portal_otp_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='dealclientportalotp',
            index=models.Index(fields=['expires_at'], name='deal_portal_otp_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='dealclientportalsession',
            index=models.Index(fields=['deal', 'email', '-created_at'], name='deal_portal_sess_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='dealclientportalsession',
            index=models.Index(fields=['expires_at'], name='deal_portal_sess_exp_idx'),
        ),
    ]
