# Generated by Django 5.2.13 on 2026-05-06 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0019_dealclientmessage_dealclientmessageattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('layout', 'Планировки'), ('photo', 'Фото'), ('video', 'Видео')], max_length=20)),
                ('module_group', models.CharField(choices=[('m1', '1 Модуль'), ('m2', '2 Модуля'), ('m3', '3 Модуля'), ('m4', '4 Модуля'), ('m5', '5 Модулей'), ('m6plus', '6+ Модулей')], max_length=20)),
                ('relative_path', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_library_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='libraryasset',
            index=models.Index(fields=['section', 'module_group', '-updated_at'], name='library_asset_list_idx'),
        ),
    ]
