# Generated by Django 5.2.13 on 2026-05-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0020_libraryasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryasset',
            name='section',
            field=models.CharField(
                choices=[
                    ('layout', 'Планировки'),
                    ('contract_template', 'Шаблоны договоров'),
                    ('photo', 'Фото'),
                    ('video', 'Видео'),
                ],
                max_length=20,
            ),
        ),
    ]
