# Generated by Django 5.2.13 on 2026-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_libraryasset_contract_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryasset',
            name='section',
            field=models.CharField(
                choices=[
                    ('layout', 'Планировки'),
                    ('contract_template', 'Шаблоны договоров'),
                    ('photo', 'Фото'),
                    ('video', 'Видео'),
                    ('supplier_file', 'Файлы поставщиков'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='libraryasset',
            name='supplier_category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('finishing', 'Отделка'),
                    ('plumbing', 'Сантехника'),
                    ('electrical', 'Электрика'),
                    ('floor_heating', 'Теплые полы'),
                    ('stoves_fireplaces', 'Печи и Камины'),
                    ('windows', 'Окна'),
                    ('furniture', 'Мебель'),
                ],
                default='',
                max_length=30,
            ),
        ),
    ]
