# Generated by Django 5.2.13 on 2026-09-02 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_libraryasset_supplier_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmnikChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('general', 'Общие вопросы'), ('deal', 'Проект')], default='general', max_length=16)),
                ('title', models.CharField(blank=True, default='Новый чат', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umnik_chat_threads', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umnik_chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UmnikChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Вы'), ('assistant', 'Умник')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='deals.umnikchatthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='umnikchatthread',
            index=models.Index(fields=['user', 'kind', '-updated_at'], name='umnik_thread_user_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='umnikchatthread',
            index=models.Index(fields=['user', 'deal', '-updated_at'], name='umnik_thread_user_deal_idx'),
        ),
        migrations.AddIndex(
            model_name='umnikchatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='umnik_msg_thread_time_idx'),
        ),
    ]
