# Generated by Django 5.2.13 on 2026-05-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_name_parts_remove_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company_name', 'last_name', 'first_name', 'middle_name']},
        ),
    ]
