# Generated by Django 5.2.13 on 2026-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='portal_password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
