# Generated by Django 5.2.13 on 2026-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('designer', 'Designer'), ('production', 'Production'), ('admin', 'Admin'), ('head', 'Head')], default='manager', max_length=20),
        ),
    ]
