"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CRM_FILES_ROOT = Path(os.getenv('CRM_FILES_ROOT', BASE_DIR / 'crm_files'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'


def _split_csv(value: str):
    return [item.strip() for item in (value or '').split(',') if item.strip()]


ALLOWED_HOSTS = _split_csv(os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,SERVERARH'))
CSRF_TRUSTED_ORIGINS = _split_csv(
    os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8001,http://SERVERARH:8001')
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'clients',
    'deals',
    'tasks',
    'catalog',
    'system_settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'
ASGI_APPLICATION = 'core.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.navigation_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'chcrm'),
        'USER': os.getenv('POSTGRES_USER', 'chcrm_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'chcrm_password'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Email (used for client portal OTP)
# Defaults to console backend for local/dev.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@ch-crm.local')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.getenv('REDIS_URL', 'redis://redis:6379/0')],
        },
    },
}

# Архив планировок (умник на LAN). Пустой URL — блок на сделке показывает «не подключён».
UMNIK_URL = os.getenv('UMNIK_URL', '').strip()
UMNIK_TOKEN = os.getenv('UMNIK_TOKEN', '').strip()
UMNIK_TIMEOUT = float(os.getenv('UMNIK_TIMEOUT', '3') or 3)
UMNIK_CHAT_TIMEOUT = float(os.getenv('UMNIK_CHAT_TIMEOUT', '180') or 180)
# Базовый URL CRM, по которому умник с другой машины скачивает вложения чата.
# Напр. http://192.168.1.10:8000 — без хвостового слэша.
UMNIK_CRM_BASE_URL = os.getenv('UMNIK_CRM_BASE_URL', '').strip().rstrip('/')
# Файлы <= этого размера уходят умнику прямо в payload (base64), крупнее — по ссылке.
UMNIK_CHAT_INLINE_MAX_MB = float(os.getenv('UMNIK_CHAT_INLINE_MAX_MB', '15') or 15)
# Вариант B: та же папка вложений чата, но путём, который открывает машина умника
# (UNC \\HOST\CH-CRM\crm_files или подключённый сетевой диск). Соответствует
# CRM_FILES_ROOT. Если пусто — поле shared_path умнику не отправляется.
UMNIK_SHARED_ROOT = os.getenv('UMNIK_SHARED_ROOT', r'D:\CH-CRM\crm_files').strip().rstrip('/\\')

# Общий чат: куда складываем вложения (файлы и фото из чата).
UMNIK_CHAT_FILES_DIR = CRM_FILES_ROOT / 'umnik_chat'
UMNIK_CHAT_MAX_UPLOAD_MB = int(os.getenv('UMNIK_CHAT_MAX_UPLOAD_MB', '40') or 40)
# Разрешённые источники для «вложить файл с сервера»: Windows-префикс -> путь внутри контейнера.
# Пути внутри контейнера появляются из volume-монтирований docker-compose (ro).
UMNIK_CHAT_SOURCE_MAP = {
    r'D:\Общая_Рабочая': os.getenv('UMNIK_SRC_RABOCHAYA', '/mnt/rabochaya'),
    r'D:\Scan_Pdf': os.getenv('UMNIK_SRC_SCAN', '/mnt/scan_pdf'),
    r'D:\CH-CRM\umnik': os.getenv('UMNIK_SRC_SCAN', '/mnt/scan_pdf'),
    r'D:\CH-CRM\crm_files': str(CRM_FILES_ROOT),
}

# Телеграм-бот диспетчерской. Пусто — команда run_telegram_bot просто не стартует.
# Токен и ID группы держим ТОЛЬКО в .env, в git они не попадают.
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '').strip()
# ID группы «диспетчерская» (все боссы + бот-админ). Формат обычной группы -123456789
# или супергруппы -1001234567890. Вся переписка в этой группе — один чат с умником.
try:
    TELEGRAM_DISPATCH_CHAT_ID = int((os.getenv('TELEGRAM_DISPATCH_CHAT_ID', '0') or '0').strip())
except ValueError:
    TELEGRAM_DISPATCH_CHAT_ID = 0
# Long polling: сколько секунд держать getUpdates и таймаут запроса.
TELEGRAM_POLL_TIMEOUT = int(os.getenv('TELEGRAM_POLL_TIMEOUT', '50') or 50)
# Максимальный размер скачиваемого из телеграма файла (фото/видео/документ), МБ.
TELEGRAM_MAX_FILE_MB = int(os.getenv('TELEGRAM_MAX_FILE_MB', '45') or 45)
# HTTP-прокси до api.telegram.org. Если пусто — прямое IPv4-соединение.
# На сетях, где Telegram закрыт, тот же прокси, что OPENROUTER_PROXY у умника.
TELEGRAM_PROXY = (os.getenv('TELEGRAM_PROXY') or os.getenv('HTTPS_PROXY') or '').strip()

USE_HTTPS = os.getenv('USE_HTTPS', 'False').lower() == 'true'
SESSION_COOKIE_SECURE = USE_HTTPS
CSRF_COOKIE_SECURE = USE_HTTPS
SECURE_SSL_REDIRECT = USE_HTTPS
