# Generated by Django 5.2.13 on 2026-04-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('sqm', 'Square meter'), ('lm', 'Linear meter'), ('pcs', 'Pieces'), ('complex', 'Complex'), ('rubles', 'Rubles')], max_length=20)),
                ('category', models.CharField(choices=[('floors', 'Floors'), ('walls', 'Walls'), ('openings', 'Openings'), ('roof', 'Roof'), ('bathroom', 'Bathroom'), ('engineering', 'Engineering'), ('overhead', 'Overhead'), ('additional', 'Additional')], max_length=20)),
                ('price_material', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_work', models.DecimalField(decimal_places=2, max_digits=12)),
                ('formula_multiplier', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
