# Generated by Django 5.2.13 on 2026-04-28 09:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_costitemoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitemoption',
            name='article',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='costitemoption',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='costitemoption',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='costitemoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='costitemoption',
            name='unit',
            field=models.CharField(blank=True, choices=[('sqm', 'Square meter'), ('lm', 'Linear meter'), ('pcs', 'Pieces'), ('complex', 'Complex'), ('rubles', 'Rubles')], max_length=20),
        ),
    ]
